apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque  
data:
  {{- if .Values.adminPassword }}
  admin-password: {{ .Values.adminPassword | quote }}
  {{- else }}
  admin-password: {{ randAlphaNum 40 | quote }}
  {{- end }}